iconList = [
  {name: " Adore", url: "./icon/Adore.png"},
  {name: " Afterboom", url: "./icon/Afterboom.png"},
  {name: " Angry", url: "./icon/Angry.png"},
  {name: " Cool", url: "./icon/Cool.png"},
  {name: " Cry", url: "./icon/Cry.png"},
  {name: " Effort", url: "./icon/Effort.png"},
  {name: " Faint", url: "./icon/Faint.png"},
  {name: " Grimace", url: "./icon/Grimace.png"},
  {name: " Haha", url: "./icon/Haha.png"},
  {name: " Hehe", url: "./icon/Hehe.png"},
  {name: " Love", url: "./icon/Love.png"},
  {name: " Misdoubt", url: "./icon/Misdoubt.png"},
  {name: " Music", url: "./icon/Music.png"},
  {name: " Nothingtosay", url: "./icon/Nothingtosay.png"},
  {name: " Sad", url: "./icon/Sad.png"},
  {name: " Shame", url: "./icon/Shame.png"},
  {name: " Sleep", url: "./icon/Sleep.png"},
  {name: " Smile", url: "./icon/Smile.png"},
  {name: " Stop", url: "./icon/Stop.png"},
  {name: " What", url: "./icon/What.png"}
]
iconParm = {
  Adore: "./icon/Adore.png",
  Afterboom: "./icon/Afterboom.png",
  Angry: "./icon/Angry.png",
  Cool: "./icon/Cool.png",
  Cry: "./icon/Cry.png",
  Effort: "./icon/Effort.png",
  Faint: "./icon/Faint.png",
  Grimace: "./icon/Grimace.png",
  Haha: "./icon/Haha.png",
  Hehe: "./icon/Hehe.png",
  Love: "./icon/Love.png",
  Misdoubt: "./icon/Misdoubt.png",
  Music: "./icon/Music.png",
  Nothingtosay: "./icon/Nothingtosay.png",
  Sad: "./icon/Sad.png",
  Shame: "./icon/Shame.png",
  Sleep: "./icon/Sleep.png",
  Smile: "./icon/Smile.png",
  Stop: "./icon/Stop.png",
  What: "./icon/What.png"
}
